### ISSUE TITLE
TMDB & FlixHQ Not Working

### ISSUE THREAD

**Issue by DarkCrypt** [Debojit-mitra/You-See#1] opened 2024-06-19 07:13 UTC
TMDB & FlixHQ plays no content. Server errors.

**Comment by Debojit-mitra** [comment] 2024-06-20 13:32
the issue is related to **[Consumet API](https://github.com/consumet/api.consumet.org)**, so if they fix it it will be fixed

**Closed by Debojit-mitra** 2024-06-20 13:32 UTC

**Comment by DarkCrypt** [comment] 2024-06-20 15:10
Doubt it. This is a common issue regarding Consumet which I've seen many times.

If what you say is correct, FlixHQ should be working according to Consumet's [provider status](https://github.com/consumet/providers-status) but your app still provides no content.

Could be the endpoints?

**Comment by Debojit-mitra** [comment] 2024-06-21 20:47
I tried with my server, search and info works but the streaming link has issues
![1](https://github.com/Debojit-mitra/You-See/assets/111267268/96f1dd27-787c-4497-a197-95503e2dfbfb)

**Comment by DarkCrypt** [comment] 2024-06-21 23:53
Ok, basically the same results as your app. Everything works except for the stream link.

I wouldn't be surprised if their provider status doesn't stay updated either. I guess we'll wait and see if it fixes itself like you said.

Thank you for replying friend. God bless!
